//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrello
    {
        public int id { get; set; }
        public int codice_prodotto { get; set; }
        public int qta { get; set; }
        public Nullable<int> codice_utente { get; set; }
    }
}
