//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordini
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ordini()
        {
            this.prodottiOrdinati = new HashSet<prodottiOrdinati>();
        }
    
        public int id { get; set; }
        public System.DateTime data_ordine { get; set; }
        public Nullable<int> stato_ordine { get; set; }
    
        public virtual statiOrdine statiOrdine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prodottiOrdinati> prodottiOrdinati { get; set; }
    }
}
